#██╗░░░██╗██╗░░██╗░█████╗░  ███╗░░░███╗███████╗███████╗████████╗██╗░░░██╗██████╗░
#██║░░░██║██║░░██║██╔══██╗  ████╗░████║██╔════╝██╔════╝╚══██╔══╝██║░░░██║██╔══██╗
#██║░░░██║███████║██║░░╚═╝  ██╔████╔██║█████╗░░█████╗░░░░░██║░░░██║░░░██║██████╔╝
#██║░░░██║██╔══██║██║░░██╗  ██║╚██╔╝██║██╔══╝░░██╔══╝░░░░░██║░░░██║░░░██║██╔═══╝░
#╚██████╔╝██║░░██║╚█████╔╝  ██║░╚═╝░██║███████╗███████╗░░░██║░░░╚██████╔╝██║░░░░░
#░╚═════╝░╚═╝░░╚═╝░╚════╝░  ╚═╝░░░░░╚═╝╚══════╝╚══════╝░░░╚═╝░░░░╚═════╝░╚═╝░░░░░ by Wixent
# This plugin is created for 1.17 version

config:
  playerstostart: 3
  countdowntime: 60
  finishrestart: true
  sendcountdowntitle: true
  nocleantime: 20
  border: true
  worldborder: 400
  wbtime: 180
  bcprefix: "&6UHC Meetup &8⪼&f "
  borderprefix: "&8[&3&lBorder&8]&r "
  goldenhead: "&6Golden Head"
  axenerf: true
  scenarios:
    heavypockets: true
    timebomb: true
    noclean: false
    absorptionless: false
  seeds:
    totalseeds: 9
    1: 11071079617937
    2: 144845014575172
    3: -271973583926241
    4: -632446011456927
    5: 828786898008397
    6: 912216414204313
    7: 149829148888427
    8: 706625171064917
    9: 471484538450128

messages:
  reload: "&6UHC Meetup &rhas been reloaded"
  join: "&e%player%&6 has joined (%needplayers% needed players to start)"
  quit: "&e%player% &6has left"
  death_by_player: "&e%victim% &6has been killed by &e%killer%"
  death: "&e%victim% &6died"
  win: "&e%player% &6 won the Meetup"
  worldborder1: "&bWorldborder is shrinking in one minute"
  worldborder2: "&bWorldborder is shrinking to 100x100 for 3 minutes"
  actionbarwaiting: "&7Waiting... (%online%/%mintostart% Players to Start)"
  actionbarwb: "&bWorldborder: %wbsize%"
  titlecountdown: "&b%countdown%"
  titlestart: "&bThe Meetup has started"
  subtitlestart: "&aGL!"
  scenenabled: "&d%scenario% &7has been &aenabled"
  scendisabled: "&d%scenario% &7has been &cdisabled"
  noclean1: "&c[NoClean] You are invulnerable for %time% seconds, unless you hit someone"
  noclean2: "&c[NoClean] You are no longer invulnerable"
  scen1: "&bScenarios Enabled:"
  scen2: "&b- %scenario%"

scoreboard:
  title: "&dMeetup"
  hubscoreboard:
    - "&fPlayers:&d %online%"
    - ""
    - "&dyour.ip"
  countdownscoreboard:
    - "&fPlayers:&d %online%"
    - "&fStarting in:&d %countdown%"
    - ""
    - "&dyour.ip"
  gamescoreboard:
    - "&fPlayers Alive:&d %aliveplayers%"
    - "&fGame Time:&d %time%"
    - "&fKills:&d %kills%"
    - "&fBorder:&d %border%"
    - ""
    - "&dyour.ip"

worlds:
  lobby_world: "lobby"
  meetup_world: "meetup"

lobby:
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0


stats:
  mysql:
    enabled: false
  Played: 0

  players:



