name: MeetupUHC
version: ${project.version}
main: net.enganxe.meetupuhc.Main
api-version: 1.16
author: Wixent
description: UHC Meetup plugin for Enganxe Network
website: github.com/wixent
commands:
  uhcmeetup:
    description: Reload plugin config
    permission: meetup.admin
  stats:
    description: See the meetup stats
  worldmeetup:
    description: Go to meetup world
    permission: meetup.admin
permissions:
  meetup.admin:
    description: All Commands
    default: op