name: MeetupUHC
version: ${project.version}
main: net.enganxe.meetupuhc.Main
api-version: 1.16
author: Wixent
description: UHC Meetup plugin for Enganxe Network
website: github.com/wixent
commands:
  uhcmeetup:
    description: Info
  stats:
    description: See the meetup stats
  forcestart:
    permission: meetup.admin
    description: Starts the meetup
  examine:
    description: See inventory of player
  topstats:
    description: See Top Stats
    permission: meetup.admin
  setlobby:
    permission: meetup.admin
    description: Set Lobby Spawn
  absorptionless:
    permission: meetup.admin
    description: Toggle Scenario
  timebomb:
    permission: meetup.admin
    description: Toggle Scenario
  noclean:
    permission: meetup.admin
    description: Toggle Scenario
  heavypockets:
    permission: meetup.admin
    description: Toggle Scenario
  scen:
    description: See Enabled Scenarios

permissions:
  meetup.admin:
    description: All Commands
    default: op